progress

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,13 +1,64 @@
-name: 
+name: build, test image.
 
 on:
   push:
     branches:
       - master
     paths:
-      - # exact folder
+      - 'application/**'
+      - '.github/workflows/**'
 
 env:
+  AWS_REGION: ${{ secrets.AWS_REGION }}
 
 jobs:
-  
+  build-push:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v3
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: login to ECR
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: build docker image
+        run: |
+          docker build -t gatus ./application
+
+      - name: security test image
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: gatus:latest
+          format: table
+          exit-code: '1'
+          ignore-unfixed: true
+          vuln-type: os,library
+          severity: CRITICAL,HIGH
+      
+      - name: test gatus container
+        run: |
+          docker run -dit --rm --name gatus-app -p 8080:8080 gatus
+          sleep 10
+          if [ "$(docker ps -q -f name=gatus-app)" ]; then
+            echo "Up & running 🚀"
+          else
+            echo "Oh No! It failed 🚨" && exit 1
+          fi
+          if curl --fail http://localhost:8080 > /dev/null; then
+            echo "I am responding well 🎉"
+          else
+            echo "I can't here you buddy! 🥺" && exit 1
+          fi
+          docker stop gatus-app
+
+      - name: tag docker container
+        run: |
+          docker tag gatus:latest ${{ secrets.ECR_REPO }}:latest
